const teams = [
  { id: 'barcelona', player: 'Nirmal', name: 'Barcelona', short: 'BAR', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png' },
  { id: 'bayern', player: 'Edwin', name: 'Bayern München', short: 'BAY', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png' },
  { id: 'madrid', player: 'Dino', name: 'Real Madrid', short: 'RMA', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png' },
  { id: 'psg', player: 'Amal', name: 'PSG', short: 'PSG', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png' },
  { id: 'monaco', player: 'Aman', name: 'Monaco FC', short: 'ASM', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/174.png' },
  { id: 'bvb', player: 'Prince', name: 'BVB', short: 'BVB', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png' },
  { id: 'inter', player: 'THALA', name: 'Inter Milan', short: 'INT', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/110.png' },
  { id: 'manutd', player: 'Jinish', name: 'Manchester United', short: 'MUN', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png' },
  { id: 'brazil', player: 'Alen T', name: 'Brazil', short: 'BRA', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/205.png' },
  { id: 'norway', player: 'Anil', name: 'Norway', short: 'NOR', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/206.png' }
];
const storeKey = 'ssl-season-2-results';
const state = { results: JSON.parse(localStorage.getItem(storeKey) || '{}'), fixtures: [], filter: 'all', round: 'all' };
const byId = id => teams.find(team => team.id === id);
function generateFixtures() {
  const list = [];
  for (let leg = 0; leg < 2; leg++) for (let home = 0; home < teams.length; home++) for (let away = home + 1; away < teams.length; away++) {
    const homeId = leg ? teams[away].id : teams[home].id;
    const awayId = leg ? teams[home].id : teams[away].id;
    list.push({ id: `m${String(list.length + 1).padStart(3, '0')}`, number: list.length + 1, round: Math.floor(list.length / 6) + 1, home: homeId, away: awayId });
  }
  return list;
}
state.fixtures = generateFixtures();
function stats() {
  const map = Object.fromEntries(teams.map(team => [team.id, { ...team, mp: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, gd: 0, pts: 0 }]));
  state.fixtures.forEach(match => { const result = state.results[match.id]; if (!result) return; const home = map[match.home], away = map[match.away]; home.mp++; away.mp++; home.gf += result.home; home.ga += result.away; away.gf += result.away; away.ga += result.home; if (result.home > result.away) { home.w++; home.pts += 3; away.l++; } else if (result.home < result.away) { away.w++; away.pts += 3; home.l++; } else { home.d++; away.d++; home.pts++; away.pts++; } });
  return Object.values(map).map(team => ({ ...team, gd: team.gf - team.ga })).sort((a, b) => b.pts - a.pts || b.gd - a.gd || b.gf - a.gf);
}
function logo(team, className = '') { return `<img class="team-logo ${className}" src="${team.logo}" alt="${team.name} crest" onerror="this.outerHTML='<span class=\'logo-fallback ${className}\'>${team.short}</span>'">`; }
function save() { localStorage.setItem(storeKey, JSON.stringify(state.results)); render(); }
function formatDate(value) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Date TBC'; }
function tableRows(items) { return items.map((team, index) => `<tr><td>${String(index + 1).padStart(2, '0')}</td><td><div class="standing-team">${logo(team)}<span><b>${team.name}</b><small>${team.player}</small></span></div></td><td>${team.mp}</td><td>${team.w}</td><td>${team.d}</td><td>${team.l}</td><td>${team.gf}</td><td>${team.ga}</td><td>${team.gd > 0 ? '+' : ''}${team.gd}</td><td>${team.pts}</td></tr>`).join(''); }
function teamLine(team, value, label) { return `${logo(team)}<span><strong>${team.name}</strong><small>${team.player} · ${label}</small></span><b>${value}</b>`; }
function renderDashboard(ordered) {
  document.querySelector('#fullTable').innerHTML = tableRows(ordered);
  const completed = state.fixtures.filter(match => state.results[match.id]); const totalGoals = completed.reduce((sum, match) => sum + state.results[match.id].home + state.results[match.id].away, 0); const top = ordered[0], conceded = [...ordered].sort((a, b) => b.ga - a.ga)[0], best = [...ordered].sort((a, b) => b.gd - a.gd)[0];
  document.querySelector('#dashboardTable').innerHTML = tableRows(ordered); document.querySelector('#completedCount').textContent = completed.length; document.querySelector('#remainingCount').textContent = state.fixtures.length - completed.length; document.querySelector('#goalCount').textContent = totalGoals; document.querySelector('#averageGoals').textContent = completed.length ? (totalGoals / completed.length).toFixed(1) : '0.0'; document.querySelector('#progressRing').style.background = `conic-gradient(var(--green) ${completed.length / 110 * 360}deg, rgba(255,255,255,.1) 0deg)`;
  document.querySelector('#topAttackLogo').innerHTML = logo(top); document.querySelector('#topAttackName').textContent = top.gf ? top.name : 'The race starts here'; document.querySelector('#topAttackPlayer').textContent = top.gf ? `${top.player} · ${top.gf} goals for` : 'Enter results to reveal the leading attack'; document.querySelector('#topAttackGoals').textContent = top.gf; document.querySelector('#mostConceded').innerHTML = teamLine(conceded, conceded.ga, 'goals conceded'); document.querySelector('#bestDifference').innerHTML = teamLine(best, `${best.gd > 0 ? '+' : ''}${best.gd}`, 'goal difference');
  const latest = [...completed].pop(), next = state.fixtures.find(match => !state.results[match.id]);
  document.querySelector('#latestMatch').outerHTML = latest ? `<div id="latestMatch" class="scoreboard"><span class="score-round">ROUND ${String(latest.round).padStart(2, '0')}</span><div class="score-teams"><div class="score-team">${logo(byId(latest.home))}<strong>${byId(latest.home).name}</strong><small>${byId(latest.home).player}</small></div><b class="score-value">${state.results[latest.id].home} — ${state.results[latest.id].away}</b><div class="score-team">${logo(byId(latest.away))}<strong>${byId(latest.away).name}</strong><small>${byId(latest.away).player}</small></div></div><small class="score-date">${formatDate(state.results[latest.id].date)} · FINAL</small></div>` : `<div id="latestMatch" class="scoreboard empty-scoreboard"><span class="score-round">ROUND 01</span><strong>Awaiting first result</strong><small>Use Admin to record a completed fixture</small></div>`;
  document.querySelector('#latestDate').textContent = latest ? formatDate(state.results[latest.id].date) : 'No completed fixtures'; document.querySelector('#latestStatus').textContent = latest ? 'FINAL' : 'SCHEDULED';
  document.querySelector('#nextNumber').textContent = next ? `MATCH ${String(next.number).padStart(3, '0')}` : 'COMPLETE'; document.querySelector('#nextRound').textContent = next ? `ROUND ${String(next.round).padStart(2, '0')}` : 'SEASON OVER'; document.querySelector('#nextDate').textContent = next && state.results[next.id]?.date ? formatDate(state.results[next.id].date) : 'Date TBC'; document.querySelector('#nextMatch').innerHTML = next ? `<div class="next-match">${logo(byId(next.home))}<strong>${byId(next.home).name}</strong><span class="vs">VS</span>${logo(byId(next.away))}<strong>${byId(next.away).name}</strong></div>` : '<div class="next-match"><strong>All scheduled matches completed</strong></div>'; document.querySelector('#tickerText').textContent = completed.length ? `${completed.length} matches completed · ${state.fixtures.length - completed.length} still to play` : 'Waiting for the opening whistle';
}
function renderMatches() { const list = state.fixtures.filter(match => state.filter === 'all' || (state.filter === 'completed' ? state.results[match.id] : !state.results[match.id])); document.querySelector('#matchList').innerHTML = list.map(match => { const result = state.results[match.id], home = byId(match.home), away = byId(match.away); return `<article class="match-card"><div class="date">MATCH ${String(match.number).padStart(3, '0')}<br>ROUND ${String(match.round).padStart(2, '0')}</div><div class="teams">${logo(home)}<strong>${home.name}</strong><b class="result-score">${result ? `${result.home} — ${result.away}` : 'VS'}</b><strong>${away.name}</strong>${logo(away)}</div><div class="result-badge ${result ? '' : 'upcoming-badge'}">${result ? 'COMPLETED' : 'UPCOMING'}</div></article>`; }).join('') || '<div class="panel empty-message">No matches in this view.</div>'; }
function renderFixtures() { const rounds = [...new Set(state.fixtures.map(match => match.round))]; document.querySelector('#roundFilters').innerHTML = '<button class="filter active" data-round="all">All rounds</button>' + rounds.map(round => `<button class="filter" data-round="${round}">Round ${String(round).padStart(2, '0')}</button>`).join(''); const list = state.fixtures.filter(match => state.round === 'all' || match.round === Number(state.round)); document.querySelector('#fixtureList').innerHTML = list.map(match => { const result = state.results[match.id], home = byId(match.home), away = byId(match.away); return `<article class="fixture-card"><div class="round-label">R${String(match.round).padStart(2, '0')}<small> / ${String(match.number).padStart(3, '0')}</small></div><div class="teams">${logo(home)}<strong>${home.name}</strong><b class="result-score">${result ? `${result.home} — ${result.away}` : '—'}</b><strong>${away.name}</strong>${logo(away)}</div><div class="fixture-state">${result ? formatDate(result.date) : 'UPCOMING'}</div></article>`; }).join(''); document.querySelectorAll('[data-round]').forEach(button => button.classList.toggle('active', String(state.round) === button.dataset.round)); }
function renderStats(ordered) { const top = ordered[0], conceded = [...ordered].sort((a, b) => b.ga - a.ga)[0], lowest = [...ordered].sort((a, b) => a.ga - b.ga)[0], best = [...ordered].sort((a, b) => b.gd - a.gd)[0]; document.querySelector('#statsLarge').innerHTML = [[top, top.gf, 'MOST GOALS SCORED', 'featured'], [conceded, conceded.ga, 'MOST GOALS CONCEDED', ''], [lowest, lowest.ga, 'LOWEST GOALS CONCEDED', ''], [best, `${best.gd > 0 ? '+' : ''}${best.gd}`, 'BEST GOAL DIFFERENCE', '']].map(([team, value, label, cls]) => `<article class="panel stat-block ${cls}"><p class="eyebrow">${label}</p><div class="stat-value">${value}</div><h2>${team.name}</h2><p>${team.player} · ${team.mp} matches played</p></article>`).join(''); }
function renderTeams(ordered) { document.querySelector('#teamGrid').innerHTML = ordered.map(team => `<article class="team-card"><div class="team-card-head">${logo(team)}<div><h2>${team.name}</h2><p>${team.player}</p></div></div><div class="team-mini-stats"><span><b>${team.mp}</b><small>MP</small></span><span><b>${team.gf}</b><small>GF</small></span><span><b>${team.gd > 0 ? '+' : ''}${team.gd}</b><small>GD</small></span><span><b>${team.pts}</b><small>PTS</small></span></div></article>`).join(''); }
function renderInter() { const team = stats().find(item => item.id === 'inter'); document.querySelector('#interStats').innerHTML = [['MP', team.mp], ['W', team.w], ['D', team.d], ['L', team.l], ['GF', team.gf], ['GA', team.ga], ['GD', team.gd], ['PTS', team.pts]].map(([label, value]) => `<span><b>${value}</b><small>${label}</small></span>`).join(''); document.querySelector('#interFixtures').innerHTML = state.fixtures.filter(match => match.home === 'inter' || match.away === 'inter').map(match => { const opponent = byId(match.home === 'inter' ? match.away : match.home), result = state.results[match.id], isHome = match.home === 'inter'; let outcome = '', score = 'UPCOMING'; if (result) { score = isHome ? `${result.home} — ${result.away}` : `${result.away} — ${result.home}`; outcome = result.home === result.away ? 'draw' : ((isHome && result.home > result.away) || (!isHome && result.away > result.home) ? 'win' : 'loss'); } return `<div class="inter-fixture"><span>${logo(opponent)}</span><span><b>${isHome ? 'Home' : 'Away'} vs ${opponent.name}</b><small>${result ? formatDate(result.date) : `Round ${match.round}`}</small></span><b class="${outcome}">${score}</b></div>`; }).join(''); }
function renderChampion(ordered) { const view = document.querySelector('#championView'); if (state.fixtures.every(match => state.results[match.id])) { const champ = ordered[0]; view.innerHTML = `<p class="eyebrow">THE FINAL WHISTLE</p><h1>Season 02<br><em>Champion</em></h1><div class="trophy">🏆</div><h2>${champ.name}</h2><p>${champ.player} · ${champ.pts} points · ${champ.gf} goals · ${champ.gd > 0 ? '+' : ''}${champ.gd} GD</p>`; } }
function render() { const ordered = stats(); renderDashboard(ordered); renderStats(ordered); renderTeams(ordered); renderFixtures(); renderMatches(); renderInter(); renderChampion(ordered); populateSelect(); }
function populateSelect() { const select = document.querySelector('#matchSelect'); if (!select) return; const current = document.querySelector('#editingMatch').value; select.innerHTML = state.fixtures.map(match => { const result = state.results[match.id]; return `<option value="${match.id}" ${match.id === current ? 'selected' : ''}>${String(match.number).padStart(3, '0')} · ${byId(match.home).name} vs ${byId(match.away).name}${result ? ' · COMPLETE' : ''}</option>`; }).join(''); }
function loadSelectedResult(id) { const result = state.results[id]; document.querySelector('#editingMatch').value = id; document.querySelector('#homeScore').value = result ? result.home : ''; document.querySelector('#awayScore').value = result ? result.away : ''; document.querySelector('#matchDate').value = result?.date || ''; document.querySelector('#deleteResult').style.display = result ? 'block' : 'none'; }
function openAdmin(matchId = '') { const dialog = document.querySelector('#adminDialog'); document.querySelector('#pinGate').classList.remove('hidden'); document.querySelector('#resultFields').classList.add('hidden'); document.querySelector('#pinInput').value = ''; document.querySelector('#pinError').textContent = ''; document.querySelector('#editingMatch').value = matchId; dialog.showModal(); }
document.querySelectorAll('[data-view-link]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); const view = link.dataset.viewLink; document.querySelectorAll('.view').forEach(item => item.classList.toggle('active', item.id === `view-${view}`)); document.querySelectorAll('[data-view-link]').forEach(item => item.classList.toggle('active', item.dataset.viewLink === view)); document.querySelector('#mainNav').classList.remove('open'); history.replaceState(null, '', `#${view}`); window.scrollTo({ top: 0, behavior: 'smooth' }); }));
document.querySelector('#mobileMenu').addEventListener('click', () => document.querySelector('#mainNav').classList.toggle('open')); document.querySelector('#adminTrigger').addEventListener('click', () => openAdmin()); document.querySelector('#heroAdmin').addEventListener('click', () => openAdmin()); document.querySelector('#unlockAdmin').addEventListener('click', () => { if (document.querySelector('#pinInput').value === '2202') { document.querySelector('#pinGate').classList.add('hidden'); document.querySelector('#resultFields').classList.remove('hidden'); populateSelect(); } else document.querySelector('#pinError').textContent = 'Incorrect PIN. Try again.'; });
document.querySelector('#adminForm').addEventListener('submit', event => { event.preventDefault(); const id = document.querySelector('#matchSelect').value; state.results[id] = { home: Number(document.querySelector('#homeScore').value), away: Number(document.querySelector('#awayScore').value), date: document.querySelector('#matchDate').value }; save(); document.querySelector('#adminDialog').close(); }); document.querySelector('#deleteResult').addEventListener('click', () => { const id = document.querySelector('#matchSelect').value; if (state.results[id] && confirm('Delete this result?')) { delete state.results[id]; save(); document.querySelector('#adminDialog').close(); } }); document.querySelector('#resetTournament').addEventListener('click', () => { if (confirm('Reset every saved result?')) { state.results = {}; save(); document.querySelector('#adminDialog').close(); } });
document.addEventListener('click', event => { const matchFilter = event.target.closest('[data-match-filter]'); if (matchFilter) { state.filter = matchFilter.dataset.matchFilter; document.querySelectorAll('[data-match-filter]').forEach(item => item.classList.toggle('active', item === matchFilter)); renderMatches(); } const round = event.target.closest('[data-round]'); if (round) { state.round = round.dataset.round; renderFixtures(); } });
render();
document.querySelector('#unlockAdmin').addEventListener('click', () => { document.querySelectorAll('#matchSelect option').forEach(option => { option.disabled = false; }); loadSelectedResult(document.querySelector('#matchSelect').value); });
document.querySelector('#matchSelect').addEventListener('change', event => loadSelectedResult(event.target.value));
