create table if not exists public.link_views (
  id bigint generated by default as identity primary key,
  player_id text not null,
  viewed_at timestamptz not null default now()
);

alter table public.link_views enable row level security;

drop policy if exists "Anyone can record a player link view" on public.link_views;
create policy "Anyone can record a player link view"
  on public.link_views for insert
  to anon
  with check (player_id in ('barcelona', 'bayern', 'madrid', 'psg', 'monaco', 'bvb', 'inter', 'manutd', 'brazil', 'argentina', 'norway'));

drop policy if exists "Anyone can read link views" on public.link_views;
create policy "Anyone can read link views"
  on public.link_views for select
  to anon
  using (true);
