create table if not exists public.link_views (
  id bigint generated by default as identity primary key,
  player_id text not null,
  viewed_at timestamptz not null default now()
);

create table if not exists public.match_results (
  match_id text primary key,
  home_score integer not null check (home_score >= 0),
  away_score integer not null check (away_score >= 0),
  match_date date,
  updated_at timestamptz not null default now()
);

alter table public.match_results enable row level security;

drop policy if exists "Anyone can read match results" on public.match_results;
create policy "Anyone can read match results"
  on public.match_results for select
  to anon
  using (true);

drop policy if exists "Admin can write match results" on public.match_results;
create policy "Admin can write match results"
  on public.match_results for all
  to anon
  using (true)
  with check (true);

alter table public.link_views enable row level security;

drop policy if exists "Anyone can record a player link view" on public.link_views;
create policy "Anyone can record a player link view"
  on public.link_views for insert
  to anon
  with check (player_id in ('barcelona', 'bayern', 'madrid', 'psg', 'monaco', 'bvb', 'inter', 'manutd', 'brazil', 'norway'));

drop policy if exists "Anyone can read link views" on public.link_views;
create policy "Anyone can read link views"
  on public.link_views for select
  to anon
  using (true);
